import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import type pg from "pg";

/** Directory with the plain-SQL migrations generated by drizzle-kit. */
export const defaultMigrationsFolder = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../migrations",
);

const MIGRATION_LOCK = 727274;

/**
 * Applies pending migrations. Safe to run concurrently from several console
 * instances: a session advisory lock serialises them. Session locks belong to
 * one connection, so the lock, the migrations and the unlock all run on a
 * single client checked out of the pool (a pooled `db.execute` could lock on
 * one connection and unlock on another, leaving the lock held).
 */
export async function runMigrations(
  pool: pg.Pool,
  migrationsFolder = defaultMigrationsFolder,
): Promise<void> {
  const client = await pool.connect();
  let failure: Error | undefined;
  try {
    await client.query(`select pg_advisory_lock(${MIGRATION_LOCK})`);
    try {
      await migrate(drizzle({ client }), { migrationsFolder, migrationsSchema: "drizzle" });
    } finally {
      await client.query(`select pg_advisory_unlock(${MIGRATION_LOCK})`);
    }
  } catch (error) {
    failure = error instanceof Error ? error : new Error(String(error));
    throw error;
  } finally {
    // A failed client is discarded instead of going back to the pool, so a
    // lock it might still hold dies with the connection.
    client.release(failure);
  }
}
