import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";

/** Directory with the plain-SQL migrations generated by drizzle-kit. */
export const defaultMigrationsFolder = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../migrations",
);

/**
 * Applies pending migrations. Safe to run concurrently from several console
 * instances: drizzle runs them in a transaction guarded by its journal table,
 * and we additionally take a session advisory lock.
 */
export async function runMigrations(
  db: NodePgDatabase<Record<string, unknown>>,
  migrationsFolder = defaultMigrationsFolder,
): Promise<void> {
  await db.execute("select pg_advisory_lock(727274)");
  try {
    await migrate(db, { migrationsFolder, migrationsSchema: "drizzle" });
  } finally {
    await db.execute("select pg_advisory_unlock(727274)");
  }
}
