import { readFileSync } from "node:fs";
import { expect, it } from "vitest";
import {
  type ActionIr,
  bindLists,
  type Expression,
  ExpressionError,
  evaluate,
  type Phase,
  parseExpression,
  validActionIr,
  validatePattern,
} from "../src/index";

// Generated by scripts/vectors.mjs; edgeweir-node keeps a copy in test/lua/expression-vectors.json
// (Lua evaluates the accepted vectors with PCRE2, Go validates all of them and runs RE2).
// An accepted vector may carry the compiled action of its rule; `actionRejected` marks actions
// nodes refuse in that phase (the expression itself stays valid).
type Vector = { source: string; phase: Phase; ir: Expression } & (
  | {
      rejected?: undefined;
      request: Record<string, string | number | boolean>;
      lists: Record<string, string[]>;
      expected: boolean;
      action?: ActionIr;
      actionRejected?: true;
      reason?: string;
    }
  | { rejected: true; reason: string }
);
const vectors: Vector[] = JSON.parse(
  readFileSync(new URL("./vectors.json", import.meta.url), "utf8"),
);
it.each(vectors.flatMap((v) => (v.rejected ? [] : [v])))(
  "shared TS/Lua vector: $source",
  ({ source, phase, ir, request, lists, expected }) => {
    expect(bindLists(parseExpression(source, phase as Phase), { blocked: "list-1" })).toEqual(ir);
    expect(evaluate(ir, request, lists)).toBe(expected);
  },
);
it.each(vectors.flatMap((v) => (v.rejected ? [v] : [])))(
  "shared rejected pattern: $source ($reason)",
  ({ source, phase, ir }) => {
    expect(() => parseExpression(source, phase)).toThrow(ExpressionError);
    expect(() => validatePattern(ir.value)).toThrow(ExpressionError);
  },
);
it.each(vectors.flatMap((v) => (!v.rejected && v.action ? [v] : [])))(
  "shared action vector: $phase $action.kind",
  ({ phase, action, actionRejected }) => {
    expect(validActionIr(phase, action as ActionIr)).toBe(!actionRejected);
  },
);
it("covers tls.ja4 and every challenge type", () => {
  const accepted = vectors.flatMap((v) => (v.rejected || v.actionRejected ? [] : [v]));
  expect(accepted.some((v) => v.ir.field === "tls.ja4")).toBe(true);
  expect(
    new Set(accepted.flatMap((v) => (v.action?.kind === "challenge" ? [v.action.challenge] : []))),
  ).toEqual(new Set(["cookie302", "js", "pow", "captcha"]));
  expect(vectors.filter((v) => !v.rejected && v.actionRejected).length).toBeGreaterThan(0);
  expect(vectors.some((v) => v.rejected && v.ir.field === "tls.ja4")).toBe(true);
});
