import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  type ActionIr,
  bindLists,
  type Expression,
  ExpressionError,
  evaluate,
  evaluateValue,
  mediaType,
  type Phase,
  parseExpression,
  parseValueExpression,
  pathExtension,
  type StructuredCacheCondition,
  structuredCacheCondition,
  structuredCacheMatch,
  validActionIr,
  validatePattern,
  validExpressionIr,
} from "../src/index";

// Generated by scripts/vectors.mjs; edgeweir-node keeps a copy in test/lua/expression-vectors.json
// (Lua evaluates the accepted vectors with PCRE2, Go validates all of them and runs RE2).
// An accepted vector may carry the compiled action of its rule; `actionRejected` marks actions
// nodes refuse in that phase (the expression itself stays valid). Value vectors (`value`) are
// redirect targets and rewrite paths with the string the node computes; `irRejected` vectors
// pair a refused source with the IR nodes must refuse; `structured` vectors are cache rule
// conditions that older nodes read in their structured form; `derive` vectors are fields the
// node derives from the request.
type Accepted = {
  source: string;
  phase: Phase;
  ir: Expression;
  rejected?: undefined;
  derive?: undefined;
  request: Record<string, string | number | boolean>;
  lists: Record<string, string[]>;
  action?: ActionIr;
  actionRejected?: true;
  reason?: string;
  structured?: StructuredCacheCondition;
} & ({ value?: undefined; expected: boolean } | { value: true; expected: string });
type Rejected = {
  source: string;
  phase: Phase;
  ir: Expression;
  rejected: true;
  derive?: undefined;
  irRejected?: true;
  value?: true;
  reason: string;
};
type Derived = { derive: "extension" | "media_type"; input: string; expected: string };
type Vector = Accepted | Rejected | Derived;
const vectors: Vector[] = JSON.parse(
  readFileSync(new URL("./vectors.json", import.meta.url), "utf8"),
);
const accepted = vectors.flatMap((v) => (!v.derive && !v.rejected ? [v as Accepted] : []));
const rejected = vectors.flatMap((v) => (!v.derive && v.rejected ? [v as Rejected] : []));

it.each(accepted.flatMap((v) => (v.value ? [] : [v])))(
  "shared TS/Lua vector: $source",
  ({ source, phase, ir, request, lists, expected, structured }) => {
    const maxLength = phase === "cache" ? 16384 : 4096;
    expect(bindLists(parseExpression(source, phase, { maxLength }), { blocked: "list-1" })).toEqual(
      ir,
    );
    expect(validExpressionIr(ir, phase)).toBe(true);
    expect(evaluate(ir, request, lists)).toBe(expected);
    if (structured)
      expect(structuredCacheMatch(structured, String(request["http.request.uri.path"]))).toBe(
        expected,
      );
  },
);
it.each(accepted.flatMap((v) => (v.value ? [v] : [])))(
  "shared value vector: $source",
  ({ source, phase, ir, request, expected }) => {
    expect(parseValueExpression(source, phase)).toEqual(ir);
    expect(validExpressionIr(ir, phase, true)).toBe(true);
    expect(validExpressionIr(ir, phase, false)).toBe(false);
    expect(evaluateValue(ir, request)).toBe(expected);
  },
);
it.each(rejected.filter((v) => !v.irRejected))(
  "shared rejected pattern: $source ($reason)",
  ({ source, phase, ir }) => {
    expect(() => parseExpression(source, phase)).toThrow(ExpressionError);
    expect(() => validatePattern(ir.value)).toThrow(ExpressionError);
  },
);
it.each(rejected.filter((v) => v.irRejected))(
  "shared rejected IR: $source ($reason)",
  ({ source, phase, ir, value }) => {
    expect(() =>
      value ? parseValueExpression(source, phase) : parseExpression(source, phase),
    ).toThrow(ExpressionError);
    expect(validExpressionIr(ir, phase, value === true)).toBe(false);
  },
);
it.each(accepted.flatMap((v) => (v.action ? [v] : [])))(
  "shared action vector: $phase $action.kind ($reason)",
  ({ phase, action, actionRejected }) => {
    expect(validActionIr(phase, action as ActionIr)).toBe(!actionRejected);
  },
);
it.each(vectors.flatMap((v) => (v.derive ? [v] : [])))(
  "shared derived field: $derive $input",
  ({ derive, input, expected }) => {
    expect((derive === "extension" ? pathExtension : mediaType)(input)).toBe(expected);
  },
);
it("covers tls.ja4 and every challenge type", () => {
  const plain = accepted.filter((v) => !v.actionRejected);
  expect(plain.some((v) => v.ir.field === "tls.ja4")).toBe(true);
  expect(
    new Set(plain.flatMap((v) => (v.action?.kind === "challenge" ? [v.action.challenge] : []))),
  ).toEqual(new Set(["cookie302", "js", "pow", "captcha"]));
  expect(
    vectors.filter((v) => !v.derive && !v.rejected && v.actionRejected).length,
  ).toBeGreaterThan(0);
  expect(rejected.some((v) => v.ir.field === "tls.ja4")).toBe(true);
});
describe("rules-v2 coverage", () => {
  const calls = (e: Expression): string[] => [
    ...(e.op === "call" ? [e.field] : []),
    ...e.children.flatMap(calls),
  ];
  it("uses every function in accepted vectors and rejects each misuse", () => {
    const used = new Set(accepted.flatMap((v) => calls(v.ir)));
    expect(used).toEqual(
      new Set([
        "lower",
        "upper",
        "len",
        "starts_with",
        "ends_with",
        "url_decode",
        "concat",
        "regex_replace",
        "wildcard_replace",
      ]),
    );
    expect(rejected.filter((v) => v.irRejected).length).toBeGreaterThanOrEqual(20);
  });
  it("covers every new action kind and field, accepted and refused", () => {
    const actions = accepted.flatMap((v) => (v.action ? [v] : []));
    const fieldsOf = (list: typeof actions) =>
      new Set(list.flatMap((v) => Object.keys(v.action as ActionIr)));
    const ok = fieldsOf(actions.filter((v) => !v.actionRejected));
    for (const field of [
      "target",
      "preserveQuery",
      "setQuery",
      "removeQuery",
      "originGroup",
      "hostHeader",
      "sni",
      "port",
      "compression",
      "brotli",
      "zstd",
      "websocket",
      "underAttack",
      "ccEnabled",
      "ccMaxLevel",
      "originConnectTimeoutMs",
      "originSendTimeoutMs",
      "originReadTimeoutMs",
      "logSampleRate",
    ])
      expect(ok.has(field), field).toBe(true);
    const refusedKinds = new Set(
      actions.filter((v) => v.actionRejected).map((v) => (v.action as ActionIr).kind),
    );
    for (const kind of ["origin", "config", "compression", "redirect", "rewrite"])
      expect(refusedKinds.has(kind), kind).toBe(true);
  });
  it("keeps every structured cache condition in its structured form", () => {
    for (const v of accepted.filter((x) => x.structured)) {
      const back = structuredCacheCondition(v.ir) as StructuredCacheCondition;
      const s = v.structured as StructuredCacheCondition;
      expect(back).toEqual({
        pathPrefixes: s.pathPrefixes,
        paths: [...s.paths].sort(),
        extensions: [...s.extensions].sort(),
      });
    }
  });
});
