import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  type ActionIr,
  bindLists,
  bodyFields,
  bodyFunctions,
  botFields,
  cookieValue,
  type Expression,
  ExpressionError,
  evaluate,
  evaluateHeaderValue,
  evaluateValue,
  isRulesV3Field,
  mediaType,
  needsRulesV3,
  type Phase,
  parseExpression,
  parseValueExpression,
  pathExtension,
  queryArgValue,
  requestPhases,
  rulesV3Fields,
  rulesV3Functions,
  type StructuredCacheCondition,
  structuredCacheCondition,
  structuredCacheMatch,
  validActionIr,
  validatePattern,
  validExpressionIr,
} from "../src/index";

// Generated by scripts/vectors.mjs; edgeweir-node keeps a copy in test/lua/expression-vectors.json
// (Lua evaluates the accepted vectors with PCRE2, Go validates all of them and runs RE2).
// An accepted vector may carry the compiled action of its rule; `actionRejected` marks actions
// nodes refuse in that phase (the expression itself stays valid). Value vectors (`value`) are
// redirect targets and rewrite paths with the string the node computes; `irRejected` vectors
// pair a refused source with the IR nodes must refuse; `structured` vectors are cache rule
// conditions that older nodes read in their structured form; `derive` vectors are fields the
// node derives from the request (cookies and query parameters by name: from the Cookie header
// and the query string). `header` value vectors are header values (rules-v3): the value set, or
// null when the node skips the header action.
type Accepted = {
  source: string;
  phase: Phase;
  ir: Expression;
  rejected?: undefined;
  derive?: undefined;
  request: Record<string, string | number | boolean>;
  lists: Record<string, string[]>;
  action?: ActionIr;
  actionRejected?: true;
  /** A platform rule's action (only those may ban at platform scope). */
  platform?: true;
  reason?: string;
  structured?: StructuredCacheCondition;
} & (
  | { value?: undefined; header?: undefined; expected: boolean }
  | { value: true; header?: undefined; expected: string }
  | { value: true; header: true; expected: string | null }
);
type Rejected = {
  source: string;
  phase: Phase;
  ir: Expression;
  rejected: true;
  derive?: undefined;
  irRejected?: true;
  value?: true;
  reason: string;
};
type Derived =
  | { derive: "extension" | "media_type"; input: string; expected: string }
  | { derive: "cookie" | "arg"; input: string; name: string; expected: string };
type Vector = Accepted | Rejected | Derived;
const vectors: Vector[] = JSON.parse(
  readFileSync(new URL("./vectors.json", import.meta.url), "utf8"),
);
const accepted = vectors.flatMap((v) => (!v.derive && !v.rejected ? [v as Accepted] : []));
const rejected = vectors.flatMap((v) => (!v.derive && v.rejected ? [v as Rejected] : []));

it.each(accepted.flatMap((v) => (v.value ? [] : [v])))(
  "shared TS/Lua vector: $source",
  ({ source, phase, ir, request, lists, expected, structured }) => {
    const maxLength = phase === "cache" ? 16384 : 4096;
    expect(bindLists(parseExpression(source, phase, { maxLength }), { blocked: "list-1" })).toEqual(
      ir,
    );
    expect(validExpressionIr(ir, phase)).toBe(true);
    expect(evaluate(ir, request, lists)).toBe(expected);
    if (structured)
      expect(structuredCacheMatch(structured, String(request["http.request.uri.path"]))).toBe(
        expected,
      );
  },
);
it.each(accepted.flatMap((v) => (v.value ? [v] : [])))(
  "shared value vector: $source",
  ({ source, phase, ir, request, expected, header }) => {
    expect(parseValueExpression(source, phase)).toEqual(ir);
    expect(validExpressionIr(ir, phase, true)).toBe(true);
    expect(validExpressionIr(ir, phase, false)).toBe(false);
    if (header) expect(evaluateHeaderValue(ir, request)).toBe(expected);
    else expect(evaluateValue(ir, request)).toBe(expected);
  },
);
it.each(rejected.filter((v) => !v.irRejected))(
  "shared rejected pattern: $source ($reason)",
  ({ source, phase, ir }) => {
    expect(() => parseExpression(source, phase)).toThrow(ExpressionError);
    expect(() => validatePattern(ir.value)).toThrow(ExpressionError);
  },
);
it.each(rejected.filter((v) => v.irRejected))(
  "shared rejected IR: $source ($reason)",
  ({ source, phase, ir, value }) => {
    expect(() =>
      value ? parseValueExpression(source, phase) : parseExpression(source, phase),
    ).toThrow(ExpressionError);
    expect(validExpressionIr(ir, phase, value === true)).toBe(false);
  },
);
it.each(accepted.flatMap((v) => (v.action ? [v] : [])))(
  "shared action vector: $phase $action.kind ($reason)",
  ({ phase, action, actionRejected, platform }) => {
    expect(validActionIr(phase, action as ActionIr, platform === true)).toBe(!actionRejected);
  },
);
it.each(vectors.flatMap((v) => (v.derive ? [v] : [])))(
  "shared derived field: $derive $input",
  (v) => {
    if (v.derive === "cookie" || v.derive === "arg")
      expect((v.derive === "cookie" ? cookieValue : queryArgValue)(v.input, v.name)).toBe(
        v.expected,
      );
    else expect((v.derive === "extension" ? pathExtension : mediaType)(v.input)).toBe(v.expected);
  },
);
it("covers tls.ja4 and every challenge type", () => {
  const plain = accepted.filter((v) => !v.actionRejected);
  expect(plain.some((v) => v.ir.field === "tls.ja4")).toBe(true);
  expect(
    new Set(plain.flatMap((v) => (v.action?.kind === "challenge" ? [v.action.challenge] : []))),
  ).toEqual(new Set(["cookie302", "js", "pow", "captcha"]));
  expect(
    vectors.filter((v) => !v.derive && !v.rejected && v.actionRejected).length,
  ).toBeGreaterThan(0);
  expect(rejected.some((v) => v.ir.field === "tls.ja4")).toBe(true);
});
describe("rules-v2 coverage", () => {
  const calls = (e: Expression): string[] => [
    ...(e.op === "call" ? [e.field] : []),
    ...e.children.flatMap(calls),
  ];
  it("uses every function in accepted vectors and rejects each misuse", () => {
    const used = new Set(accepted.flatMap((v) => calls(v.ir)));
    expect(used).toEqual(
      new Set([
        "lower",
        "upper",
        "len",
        "starts_with",
        "ends_with",
        "url_decode",
        "concat",
        "regex_replace",
        "wildcard_replace",
        // rules-v3
        "url_encode",
        "base64_encode",
        "base64_decode",
        "md5",
        "sha1",
        "sha256",
        "substring",
        "to_string",
        // rules-body-v1
        "form_value",
        "json_value",
      ]),
    );
    expect(rejected.filter((v) => v.irRejected).length).toBeGreaterThanOrEqual(20);
  });
  it("covers every new action kind and field, accepted and refused", () => {
    const actions = accepted.flatMap((v) => (v.action ? [v] : []));
    const fieldsOf = (list: typeof actions) =>
      new Set(list.flatMap((v) => Object.keys(v.action as ActionIr)));
    const ok = fieldsOf(actions.filter((v) => !v.actionRejected));
    for (const field of [
      "target",
      "preserveQuery",
      "setQuery",
      "removeQuery",
      "originGroup",
      "hostHeader",
      "sni",
      "port",
      "compression",
      "brotli",
      "zstd",
      "websocket",
      "underAttack",
      "ccEnabled",
      "ccMaxLevel",
      "originConnectTimeoutMs",
      "originSendTimeoutMs",
      "originReadTimeoutMs",
      "logSampleRate",
    ])
      expect(ok.has(field), field).toBe(true);
    const refusedKinds = new Set(
      actions.filter((v) => v.actionRejected).map((v) => (v.action as ActionIr).kind),
    );
    for (const kind of ["origin", "config", "compression", "redirect", "rewrite"])
      expect(refusedKinds.has(kind), kind).toBe(true);
  });
  it("keeps every structured cache condition in its structured form", () => {
    for (const v of accepted.filter((x) => x.structured)) {
      const back = structuredCacheCondition(v.ir) as StructuredCacheCondition;
      const s = v.structured as StructuredCacheCondition;
      expect(back).toEqual({
        pathPrefixes: s.pathPrefixes,
        paths: [...s.paths].sort(),
        extensions: [...s.extensions].sort(),
      });
    }
  });
});
describe("rules-v3 coverage", () => {
  const walk = (e: Expression): Expression[] => [e, ...e.children.flatMap(walk)];
  const actionIrs = (v: Accepted) => [
    ...(v.action?.target ? [v.action.target] : []),
    ...(v.action?.setQuery ?? []).flatMap((p) => (p.expression ? [p.expression] : [])),
  ];
  const plain = accepted.filter((v) => !v.actionRejected);
  const nodes = plain.flatMap((v) => [v.ir, ...actionIrs(v)].flatMap(walk));
  it("reads every new field, calls every new function and uses both wildcard comparisons", () => {
    const fields = new Set(nodes.flatMap((e) => (e.op !== "call" ? [e.field] : [])));
    for (const field of rulesV3Fields) expect(fields.has(field), field).toBe(true);
    expect([...fields].some((f) => f.startsWith("http.request.cookies."))).toBe(true);
    expect([...fields].some((f) => f.startsWith("http.request.uri.args."))).toBe(true);
    const calls = new Set(nodes.flatMap((e) => (e.op === "call" ? [e.field] : [])));
    for (const name of rulesV3Functions) expect(calls.has(name), name).toBe(true);
    const ops = new Set(nodes.map((e) => e.op));
    expect(ops.has("wildcard") && ops.has("strict_wildcard")).toBe(true);
    expect(plain.filter((v) => needsRulesV3(v.ir)).length).toBeGreaterThanOrEqual(60);
  });
  it("covers missing and repeated cookies and parameters, invalid Base64 and skipped headers", () => {
    const derived = vectors.flatMap((v) =>
      v.derive === "cookie" || v.derive === "arg" ? [v] : [],
    );
    for (const kind of ["cookie", "arg"]) {
      const of = derived.filter((v) => v.derive === kind);
      expect(of.some((v) => v.expected === "" && !v.input.includes(`${v.name}=`))).toBe(true);
      expect(of.some((v) => v.input.split(v.name).length > 2)).toBe(true);
    }
    const values = plain.filter((v) => v.value);
    expect(
      values.filter((v) => v.source.startsWith("base64_decode") && v.expected === "").length,
    ).toBeGreaterThanOrEqual(5);
    expect(values.filter((v) => v.header && v.expected === null).length).toBeGreaterThanOrEqual(5);
    expect(values.some((v) => /substring\([^)]*, -/.test(v.source))).toBe(true);
  });
  it("covers every new action field, accepted and refused, and refuses new IR shapes", () => {
    const actions = accepted.flatMap((v) => (v.action ? [v] : []));
    const ok = actions.filter((v) => !v.actionRejected).map((v) => v.action as ActionIr);
    expect(ok.some((a) => a.append)).toBe(true);
    expect(ok.some((a) => a.kind === "request_header" && a.target)).toBe(true);
    expect(ok.some((a) => a.kind === "response_header" && a.target)).toBe(true);
    expect(ok.some((a) => a.setQuery?.some((p) => p.expression))).toBe(true);
    expect(ok.some((a) => a.statusCode === 303)).toBe(true);
    const refused = actions.filter((v) => v.actionRejected).map((v) => v.action as ActionIr);
    expect(refused.some((a) => a.append)).toBe(true);
    expect(refused.some((a) => a.kind.endsWith("_header") && a.target)).toBe(true);
    expect(refused.some((a) => a.setQuery?.some((p) => p.expression))).toBe(true);
    expect(
      rejected.filter((v) => v.irRejected && [v.ir, ...v.ir.children].some(needsRulesV3OrShape))
        .length,
    ).toBeGreaterThanOrEqual(15);
  });
  const needsRulesV3OrShape = (e: Expression): boolean =>
    needsRulesV3(e) || isRulesV3Field(e.field) || e.op === "strict_contains";
});

describe("G14 coverage", () => {
  const reads = (e: Expression, names: ReadonlySet<string>): boolean =>
    names.has(e.field) || e.children.some((c) => reads(c, names));
  it("covers the body and crawler fields in every request phase and refuses them elsewhere", () => {
    const body = accepted.filter(
      (v) => !v.value && reads(v.ir, new Set([...bodyFields, ...bodyFunctions])),
    );
    expect(new Set(body.map((v) => v.phase))).toEqual(requestPhases);
    for (const field of [...bodyFields, ...botFields])
      expect(
        accepted.some((v) => reads(v.ir, new Set([field]))),
        field,
      ).toBe(true);
    const refused = rejected.filter((v) => v.irRejected).map((v) => v.phase);
    for (const phase of ["cache", "response-transform", "compression"])
      expect(refused, phase).toContain(phase);
  });
  it("covers every waf-v2 action, accepted and refused", () => {
    const actions = accepted.flatMap((v) => (v.action ? [v] : []));
    const kinds = (list: typeof actions) => new Set(list.map((v) => (v.action as ActionIr).kind));
    for (const kind of ["ban", "respond", "close", "skip"]) {
      expect(kinds(actions.filter((v) => !v.actionRejected)), kind).toContain(kind);
      expect(kinds(actions.filter((v) => v.actionRejected)), kind).toContain(kind);
    }
    expect(actions.some((v) => v.platform && !v.actionRejected)).toBe(true);
    const ok = new Set(
      actions.filter((v) => !v.actionRejected).flatMap((v) => Object.keys(v.action as ActionIr)),
    );
    for (const field of [
      "banSeconds",
      "banPrefixV4",
      "banPrefixV6",
      "banScope",
      "contentType",
      "body",
      "errorPage",
      "skip",
      "accessLog",
      "crs",
    ])
      expect(ok, field).toContain(field);
  });
});
