/**
 * Every action the console writes to the audit log. `recordAudit` only takes
 * these; the web console labels each one with `audit_action_<action>` (dots
 * as underscores) and shows codes it does not know (older entries) as they are.
 */
export const auditActions = [
  "account.passkey_add",
  "account.passkey_delete",
  "account.password_change",
  "account.recover",
  "account.two_factor_disable",
  "account.two_factor_enable",
  "alert.channel_create",
  "alert.channel_delete",
  "alert.channel_test",
  "alert.channel_test_request",
  "alert.channel_update",
  "alert.policy_update",
  "alert.smtp_update",
  "alert.subscribe",
  "alert.subscription_update",
  "alert.unsubscribe",
  "api_key.create",
  "api_key.revoke",
  "acme_account.delete",
  "auth.sign_in",
  "auth.sign_in_failed",
  "ban.create",
  "ban.delete",
  "ban.update",
  "cache.prefetch",
  "cache.purge",
  "certificate.delete",
  "certificate.issued",
  "certificate.names_extended",
  "certificate.renew",
  "certificate.renewal_rescheduled",
  "certificate.request",
  "certificate.unloadable",
  "certificate.upload",
  "cluster.cache_update",
  "cluster.challenge_keys_rotate",
  "cluster.client_ip_update",
  "cluster.create",
  "cluster.delete",
  "cluster.listen_ports_update",
  "cluster.port_pools_update",
  "cluster.rollback",
  "cluster.rollout_abort",
  "cluster.rollout_direct",
  "cluster.rollout_policy_update",
  "cluster.session_ticket_keys_rotate",
  "cluster.rollout_promote",
  "cluster.rollout_rollback",
  "cluster.unknown_hosts_update",
  "cluster.update",
  "dns.applied",
  "dns.binding_update",
  "dns.force_publish",
  "dns.protection_update",
  "dns.provider_create",
  "dns.provider_delete",
  "dns.provider_update",
  "dns.rollback",
  "dns_credential.create",
  "dns_credential.delete",
  "dns_credential.update",
  "enrollment_token.create",
  "ip_list.create",
  "ip_list.delete",
  "ip_list.update",
  "l4.cname_update",
  "l4_app.create",
  "l4_app.delete",
  "l4_app.disable",
  "l4_app.enable",
  "l4_app.update",
  "node.cache_update",
  "node.certificate_renew",
  "node.delete",
  "node.disable",
  "node.enable",
  "node.enroll",
  "node.move",
  "node.set_addresses",
  "node.set_probe",
  "node.update",
  "node.upgrade_cancel",
  "node.upgrade_create",
  "node.upgrade_promote",
  "node.upgrade_result",
  "node_group.create",
  "node_group.delete",
  "node_group.update",
  "platform.rules_update",
  "probe.certificate_renew",
  "probe.delete",
  "probe.enroll",
  "probe.token_create",
  "probe.update",
  "region.create",
  "region.delete",
  "region.update",
  "scheduling.activate",
  "scheduling.recover",
  "scheduling.rule_create",
  "scheduling.rule_delete",
  "scheduling.rule_update",
  "service_account.create",
  "service_account.delete",
  "service_account.key_create",
  "service_account.key_revoke",
  "service_account.update",
  "site.access_control_update",
  "site.auth_sign_url",
  "site.auth_update",
  "site.bulk_redirects_update",
  "site.cname_update",
  "site.create",
  "site.delete",
  "site.disable",
  "site.enable",
  "site.error_pages_update",
  "site.https_update",
  "site.logs_configure",
  "site.maintenance_update",
  "site.protection_update",
  "site.purge_all",
  "site.rules_update",
  "site.update",
  "site.waf_update",
  "system.acme_directory_update",
  "system.bans_update",
  "system.cc_template_update",
  "system.error_pages_update",
  "system.node_channel_update",
  "system.origin_allow_list_update",
  "system.probes_update",
  "system.protection_update",
  "system.recompile",
  "system.release_source_update",
  "system.setup",
  "system.setup_rejected",
  "system.usage_update",
  "system.log_retention_update",
] as const;
export type AuditAction = (typeof auditActions)[number];

/** Types of the objects audit entries are about (`audit_target_<type>` in the web console). */
export const auditTargetTypes = [
  "acme_account",
  "alert_channel",
  "alert_subscription",
  "api_key",
  "ban",
  "cache_task",
  "certificate",
  "cluster",
  "dns_credential",
  "dns_provider",
  "ip_list",
  "l4_app",
  "node",
  "node_group",
  "node_upgrade",
  "platform",
  "probe",
  "region",
  "scheduling_rule",
  "service_account",
  "site",
  "system",
  "system_setting",
  "user",
] as const;
export type AuditTargetType = (typeof auditTargetTypes)[number];

/** Message key of an audit action's label: `site.create` → `audit_action_site_create`. */
export const auditActionMessageKey = (action: string) =>
  `audit_action_${action.replaceAll(".", "_")}`;

/** Message key of an audit target type's label. */
export const auditTargetMessageKey = (type: string) => `audit_target_${type}`;
